// CommonJS, every file is module(by default)
// Moudules - Encapsulated Code (only share minmum)
const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alterrative-flavor')
require('./7-mind-grenade')

// console.log(data)
// sayHi('susan')
// sayHi(names.john)
// sayHi(names.peter)